// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]" | "/[locale]/about" | "/[locale]/admin/push" | "/[locale]/branches" | "/[locale]/category/[id]" | "/[locale]/contact" | "/[locale]/farmer-meetings" | "/[locale]/product/[id]" | "/[locale]/quiz" | "/product/[id]" | "/read"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/bot-webhook" | "/api/push/send" | "/api/push/subscribe" | "/api/read" | "/api/send-telegram"
type PageRoutes = never
type LayoutRoutes = "/[locale]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/admin/push": { "locale": string; }
  "/[locale]/branches": { "locale": string; }
  "/[locale]/category/[id]": { "locale": string; "id": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/farmer-meetings": { "locale": string; }
  "/[locale]/product/[id]": { "locale": string; "id": string; }
  "/[locale]/quiz": { "locale": string; }
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/bot-webhook": {}
  "/api/push/send": {}
  "/api/push/subscribe": {}
  "/api/read": {}
  "/api/send-telegram": {}
  "/product/[id]": { "id": string; }
  "/read": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
